website/models.py
from asyncio.windows_events import NULL
from datetime import timezone
from enum import unique
from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, db.Sequence('seq_reg_id', start=1, increment=1),primary_key=True)
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    email = db.Column(db.String(50),unique = True)
    phone_number = db.Column(db.String(11))
    password = db.Column(db.String(8))
    occupation = db.Column(db.String(10))
    date_of_birth =db.Column(db.Date)
    gender = db.Column(db.String(20))

class Message(db.Model):
    email = db.Column(db.String(50),primary_key = True)
    message = db.Column(db.String(300))
   

website/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path

db = SQLAlchemy ()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'bangla bully detection using machine learning'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
        
    from .admin import admin
    from .views import views

    app.register_blueprint(admin, url_prefix='/admin')
    app.register_blueprint(views, url_prefix='/')

    from .models import User, Message
    

    create_database(app)

    return app

def create_database(app):
    if not path.exists ('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created database!')

website/views.py
import os
import sqlite3
from xmlrpc.client import boolean
import PyPDF2
from flask import Flask,flash, Blueprint, render_template, request,url_for,redirect,session
from sqlalchemy import true

from website.models import User, Message
from . import db
from werkzeug.utils import secure_filename

currentlocation = os.path.dirname(os.path.abspath(__file__))

views = Blueprint("views", __name__)

UPLOAD_FOLDER = './website/uploads'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'docx'}

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@views.route('/', methods=['GET', 'POST'])
def home():
    
 if request.method == 'POST':
        # check if the post request has the file part
    if 'file' not in request.files:
       flash('No file part')
       return redirect(request.url)
    file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
    if file.filename == '':
       flash('No selected file')
       return redirect(request.url)
    if file and allowed_file(file.filename):
       filename = secure_filename(file.filename)
       a = PyPDF2.PdfFileReader('Application form Amabassador programme.pdf')
       str = ""
       for i in range(1,10):
         str += a.getPage(i).extract_text()
       with open ("text.txt", "w") as f:
         f.write(str)
       file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
       print("File saved")

 return render_template("homepage.html")
    
   
@views.route("/login", methods=['GET', 'POST'])
def login():

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        sqlconnection = sqlite3.Connection(currentlocation + "\database.db")
        cursor = sqlconnection.cursor()
        query1 = "SELECT email, password FROM User Where email = '"+email+"'AND password = '"+password+"'".format(email=email, password = password)

        rows = cursor.execute(query1)
        rows = rows.fetchall()
        if len(rows)==0:
            flash('Invalid username or password', category ='error')
        else:
            return redirect("/")
    return render_template("login.html")
   

@views.route("/ResetPass",  methods=['GET', 'POST'])
def reset_pass():

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        sqlconnection = sqlite3.Connection(currentlocation + "\database.db")
        cursor = sqlconnection.cursor()
        query1 = "UPDATE User SET password = '"+password+"' WHERE email='"+email+"'".format(email = email,password=password)
        cursor.execute(query1)
        sqlconnection.commit()
        return redirect("/login")
    return render_template("ResetPass.html")



@views.route("/SignUp" , methods=['GET', 'POST'])
def SignUp():
    if request.method == 'POST':
        first_name = request.form.get ('first_name')
        last_name = request.form.get ('last_name')
        email = request.form.get ('email')
        phone_number = request.form.get ('phone_number')
        password = request.form.get ('password')
        occupation = request.form.get ('occupation')
        date_of_birth = request.form.get ('date_of_birth')
        gender = request.form.get('gender')

        if len(first_name) < 2:
            flash('First name must be greater than 1 character.' , category ='error')
        elif len(last_name) < 2:
            flash('Last name must be greater than 1 character.' , category ='error')
        elif len(email) < 4:
            flash('Email must be greater than 4 characters.' , category ='error')
        elif len(phone_number) < 11:
            flash('Phone number must be eleven digits.' , category ='error')
        elif len(password) < 7:
            flash('Password must be atleast 7 characters' , category ='error')

        elif len(occupation) < 6:
            flash('Password must be atleast 6 characters' , category ='error')
       
        else:
            flash('Account created', category= 'success')
            pass
            
        sqlconnection =sqlite3.Connection(currentlocation + "\database.db")
        cursor = sqlconnection.cursor()
        query1 = "INSERT INTO User VALUES('{id}','{first_name}','{last_name}','{email}','{phone_number}','{password}','{occupation}','{date_of_birth}','{gender}')".format (id = 6, first_name = first_name, last_name = last_name, email = email, phone_number = phone_number, password = password, occupation = occupation, date_of_birth = date_of_birth, gender = gender)
        cursor.execute(query1)
        sqlconnection.commit()
        return redirect("/")
    return render_template("SignUp.html")


@views.route("/profile")
def profile():
    return render_template("profile.html")


@views.route("/help")
def help():
    return render_template("help.html")


@views.route("/upload")
def upload():
    return render_template("upload.html")


@views.route("/guidence")
def guidence():
    return render_template("guidence.html")


@views.route("/userprofile")
def userprofile():
    return render_template("userprofile.html")

@views.route("/baseHome", methods=['GET', 'POST'])
def baseHome():
    if request.method == 'POST':
      email = request.form.get ('email')
      message = request.form.get('message')

      sqlconnection =sqlite3.Connection(currentlocation + "\database.db")
      cursor = sqlconnection.cursor()
      query1 = "INSERT INTO Message VALUES('{email}','{message}')".format (email = email, message = message)
      cursor.execute(query1)
      sqlconnection.commit()
      redirect("/login")
    return render_template("login.html")

@views.route("/logout")
def logout():
    return render_template("login.html")


@views.route('/details/<int:id>')
def RetrieveSingleEmployee(id):
    customer = User.query.filter_by(id=id).first()
    if customer:
        return render_template('userdetails.html', customer = customer)
    return f"Employee with id ={id} Doenst exist"

@views.route("/BaseHHome")
def BaseHHome():
    return render_template("BaseHHome.html")

website/templates/BaseHHome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- For footer -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/footer.css')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
</head>
<body>
    <header>
        <div class="dropdown">
            <nav>
                
                <label class="logo"><a>SNOOPER</a></label>
                <ul>

                    <li><a href="#"><i class="fa fa-bars"></i></a>
                        <ul>
                            <li><a class="active" href="{{url_for('views.userprofile')}}">User Profile</a></li>
                            <li><a href="{{url_for('views.logout')}}">Log out</a></li>
                        </ul>
                    </li>
                </ul>

            </nav>
        </div>
    </header>
    {% block content %}{% endblock content %}

        <footer>
            <div class="content">
                <div class="left box">
                    <div class="upper">
                        <div class="topic">About us</div>
                        <p>Bullying and aggression are increasingly worrisome</p>
                        <p>phenomena affecting people accros the world.</p>
                        <p>This is a worldwide problem for all of us</p>
                        <p>Even Banagli or messages contain various offensive words</p>
                        <p>Our software amins to detect those bullying and offensive</p>
                        <p>words.</p>
                        <p><b>Hope Our software will be able to help you.</b></p>
                        <p><b>Enjoy! &#128512; </b></p>
                    </div>
                </div>
                <div class="middle box">
                    <div class="lower">
                        <div class="topic">Contact us</div>
                        <div class="phone">
                            <a href="#"><i class="fas fa-phone-volume"></i>*********</a>
                        </div>
                        <div class="email">
                            <a href="#"><i class="fas fa-envelope"></i>abc@gmail.com</a>
                        </div>
                        <div>
                            <a href="{{url_for('views.help')}}">HELP</a>
                        </div>
                    </div>
                </div>
                <div class="right box">
                    <div class="topic">For Any Queries</div>
                    <form action="/baseHome" method="post">
                        <input type="text" placeholder="Email" name="email" id="email">
                        <!-- <input type="submit" name="" value="Send"> -->
                        <input type="text" maxlength="300" placeholder="Your Queries" name="message" id="message">
                        <input type="submit" name="" value="Send">
                    </form>
                </div>
            </div>
        </footer>

</body>
</html>

website/templates/ResetPass.html
{% extends 'baseHome.html' %} {% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Reset Password</title>
  <!-- stylesheet -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/ResetPass.css') }}" />
  <!-- materials icon -->
  <!-- https://fonts.google.com/icons?icon.style=Sharp&icon.query=close -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- header -->
  <!-- <link rel="stylesheet" href="{{url_for('static', filename='css/start.css')}}"> -->
</head>

<body>
  <div class="container">
    <form action="/ResetPass" method="post">
      <h1>Reset Password</h1>
        <label for="email">Email Address</label>
        <input type="email" placeholder="Enter Email" name="email" id="email" required>
        <label for="password">New Password</label>
        <input type="password" placeholder="Enter New Password" maxlength="12" name="password" id="password" required>
        <button type="submit"><b>Reset</b></button>
        <div class="signup_link">
          <a href="{{url_for('views.login')}}">Back to log In</a>
        </div>
      </form>
    </div>
</body>
</html>
{% endblock content %}

website/templates/SignUp.html
<!DOCTYPE html>
<!-- Created By CodingLab - www.codinglabweb.com -->
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <title> Sign Up </title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/SignUp.css')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Header -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/start.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/footer.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
    <header>
          <div class="dropdown">
            <nav>
                <label class="logo">SNOOPER</label>
            </nav>
        </div>
    </header>
{% with messages = get_flashed_messages(with_categories = true) %}
  {% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
  {% endwith %} 
  <div class="container">
    <div class="title">Sign Up for your snooper account</div>
    <div class="content">
      <form action="/SignUp" method="post">
            <div class="user-details">
                <div class="input-box">
                    <span class="details">First Name</span>
                    <input type="text" placeholder="Enter your first name" name ="first_name" id="first_name" required>
                </div>
                <div class="input-box">
                    <span class="details">Last Name</span>
                    <input type="text" placeholder="Enter your last name" name="last_name" id="last_name" required>
                </div>
                
                <div class="input-box">
                    <span class="details">Email</span>
                    <input type="email" placeholder="Enter your email" name="email" id="email" required>
                </div>
                <div class="input-box">
                    <span class="details">Phone Number</span>
                    <input type="text" placeholder="Enter your phone number" name="phone_number" id="phone_number" required>
                </div>
                <div class="input-box">
                    <span class="details">Password</span>
                    <input type="password" placeholder="Enter the password" maxlength="12" name="password" id="password" required>
                </div>
                <div class="input-box">
                    <span class="details">Occupation</span>
                    <input type="text" placeholder="Student/Employee/Businessman" name="occupation" id="occupation" required>
                </div>
                <div class="input-box">
                    <span class="details">Date Of Birth</span>
                    <input type="date" name="date_of_birth" id="date_of_birth" min="1950-01-01" max="2012-01-30">
                </div>
            </div>
            <div class="gender-details" name="gender">
                <input type="radio" name="gender" id="dot-1" value="Male"></input>
                <input type="radio" name="gender" id="dot-2" value="Female"></input>
                <input type="radio" name="gender" id="dot-3" value="Prefered not to say"></input>
                <span class="gender-title">Gender</span>
                <div class="category">
                      <label for="dot-1">
                        <span class="dot one"></span>
                        <span class="gender">Male</span>
                      </label> 
                     <label for="dot-2">
                        <span class="dot two"></span>
                        <span class="gender">Female</span>
                     </label>
                     
                  <label for="dot-3">
                        <span class="dot three"></span>
                        <span class="gender">Prefered not to say</span>
                    </label>
                    
                </div>
            </div> 
            <div class="button">
                <input type="submit" value="Sign Up">
             </div>
             <div class="signup_link">
              <a href="{{url_for('views.login')}}">Back to log In</a>
           </div>
        </form>
    </div>
</div>
  
</body>

    <footer>
        <div class="content">
            <div class="left box">
                <div class="upper">
                    <div class="topic">About us</div>
                    <p>Bullying and aggression are increasingly worrisome</p>
                  <p>phenomena affecting people accros the world.</p>
                  <p>This is a worldwide problem for all of us</p>
                  <p>Even Banagli or messages contain various offensive words</p>
                  <p>Our software amins to detect those bullying and offensive</p>
                  <p>words.</p>
                  <p><b>Hope Our software will be able to help you.</b></p>
                  <p><b>Enjoy! &#128512; </b></p>
                </div>
            </div>
            <div class="middle box">
                <div class="lower">
                    <div class="topic">Contact us</div>
                    <div class="phone">
                        <a href="#"><i class="fas fa-phone-volume"></i>*********</a>
                    </div>
                    <div class="email">
                        <a href="#"><i class="fas fa-envelope"></i>abc@gmail.com</a>
                    </div>
                </div>
            </div>
            <div class="right box">
                <div class="topic">For Any Queries</div>
                <form action="#">
                    <input type="text" placeholder="Email">
                    <input type="text" placeholder="Your Queries">
                    <input type="submit" name="" value="Send">
                </form>
            </div>
        </div>
    </footer>

</html>

website/templates/admin_dashboard.html
{% extends 'base_admin.html' %} {% block content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/admin_dashboard.css') }}"
/>
<main>
  <h1>Dashboard</h1>

  <div class="date">
    <input type="date" />
  </div>

  <div class="insights">
    <div class="total-customer">
      <span class="material-icons-sharp"> supervisor_account </span>
      <div class="middle">
        <div class="left">
          <h3>Total Customer</h3>
          <h1>110,000</h1>
        </div>
        <div class="progress">
          <svg>
            <circle cx="38" cy="38" r="36"></circle>
          </svg>
          <div class="number">
            <p>81%</p>
          </div>
        </div>
      </div>
      <small class="text-muted">Last 24hours</small>
    </div>
    <!-- END OF TOTAL CUSTOMER -->
    <div class="total-detection">
      <span class="material-icons-sharp"> bar_chart </span>
      <div class="middle">
        <div class="left">
          <h3>Total Detection</h3>
          <h1>110,000</h1>
        </div>
        <div class="progress">
          <svg>
            <circle cx="38" cy="38" r="36"></circle>
          </svg>
          <div class="number">
            <p>62%</p>
          </div>
        </div>
      </div>
      <small class="text-muted">Last 24hours</small>
    </div>
    <!-- END OF TOTAL Detection -->
    <div class="premium-customer">
      <span class="material-icons-sharp"> stacked_line_chart </span>
      <div class="middle">
        <div class="left">
          <h3>Premium Customer</h3>
          <h1>110,000</h1>
        </div>
        <div class="progress">
          <svg>
            <circle cx="38" cy="38" r="36"></circle>
          </svg>
          <div class="number">
            <p>44%</p>
          </div>
        </div>
      </div>
      <small class="text-muted">Last 24hours</small>
    </div>
    <!-- END OF Today sign-in -->
  </div>
  <!-- END OF INSIGHTS -->

  <div class="recent-customers">
    <h2>Recent Customer</h2>
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Gender</th>
          <th>Occupation</th>
          <th>Premium</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for customer in customers %}
        <tr>
          <td>{{customer.id}}</td>
          <td>{{customer.first_name}}</td>
          <td>{{customer.email}}</td>
          <td>{{customer.gender}}</td>
          <td>{{customer.occupation}}</td>
          <td class="warning">Yes</td>
          <td class="primary"><a href="/details/{{customer.id}}">details</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="#">Show All</a>
  </div>
</main>
{% endblock content %}
<!-- END OF MAIN -->

website/templates/baseHome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title></title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/footer.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/start.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- For footer -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    <header>
        <div class="dropdown">
            <nav>
                <label><a class="logo" href="{{url_for('views.home')}}">SNOOPER</a></label>
            </nav>
        </div>
    </header>
    {% block content %}{% endblock content %}
    <main>

    </main>

    <footer>
        <div class="content">
            <div class="left box">
                <div class="upper">
                    <div class="topic">About us</div>
                    <p>Bullying and aggression are increasingly worrisome</p>
                  <p>phenomena affecting people accros the world.</p>
                  <p>This is a worldwide problem for all of us</p>
                  <p>Even Banagli or messages contain various offensive words</p>
                  <p>Our software amins to detect those bullying and offensive</p>
                  <p>words.</p>
                  <p><b>Hope Our software will be able to help you.</b></p>
                  <p><b>Enjoy! &#128512; </b></p>
                </div>
            </div>
            <div class="middle box">
                <div class="lower">
                    <div class="topic">Contact us</div>
                    <div class="phone">
                        <a href="#"><i class="fas fa-phone-volume"></i>*********</a>
                    </div>
                    <div class="email">
                        <a href="#"><i class="fas fa-envelope"></i>abc@gmail.com</a>
                    </div>
                </div>
            </div>
            <div class="right box">
                <div class="topic">For Any Queries</div>
                <form action="#">
                    <input type="text" placeholder="Email">
                    <input type="text" placeholder="Your Queries">
                    <input type="submit" name="" value="Send">
                </form>
            </div>
        </div>
    </footer>

</body>
</html>

website/templates/footer.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>footer</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/footer.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col">
                    <h4><b>About us</b></h4>
                    <p>Our software aims to make </p>
                    <p>to detect offense words</p>
                   
                <div class="footer-col">
                    <h4><b>Quick Links</b></h4>
                    <div class="helpfont">
                        <li>
                            <a href="{{url_for('views.help')}}">Help</a>
                        </li>
                    </div>
                </div>
                <div class="footer-col">
                    <h4><b>Contact us</b></h4>
                    <div class="social-links">
                        <li><a href="#">Gmail<i class="glyphicon"> &#x2709;</i></a></li>
                        <li><a href="#">Phone<i class='fas'>&#xf095;</a> </li>
                        <li><a href="#">Message<i class='fas'>&#xf4ad;</a> </li>
                    </div>
                </div>
            </div>

        </div>

    </footer>

</body>
</html> -->


<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" href="{{url_for('static', filename='css/footer.css')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
</head>
<body>
    <footer>
        <div class="content">
            <div class="left box">
                <div class="upper">
                    <div class="topic">About us</div>
                    <p>Bullying and aggression are increasingly worrisome</p>
                    <p>phenomena affecting people accros the world.</p>
                    <p>Even Banagli or messages contain various offensive words</p>
                    <p>Our software amins to detect those bullying and offensive</p>
                    <p>words.</p>
                    <p><b>Hope Our software will be able to help you.</b></p>
                </div>
            </div>
            <div class="middle box">
                <div class="lower">
                    <div class="topic">Contact us</div>
                    <div class="phone">
                        <a href="#"><i class="fas fa-phone-volume"></i>*********</a>
                    </div>
                    <div class="email">
                        <a href="#"><i class="fas fa-envelope"></i>abc@gmail.com</a>
                    </div>
                </div>
            </div>
            <div class="right box">
                <div class="topic">For Any Queries</div>
                <form action="#">
                    <input type="text" placeholder="email">
                    <!-- <input type="submit" name="" value="Send"> -->
                    <input type="text" placeholder="Your Queries">
                    <input type="submit" name="" value="Send">
                </form>
            </div>
        </div>
    </footer>
</body>
</html>

website/templates/help.html
{% extends 'BaseHHome.html' %} {% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{url_for('static', filename='css/help.css')}}">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
  <h1>HELP</h1>
  
  <div class="container">
    <div class="box">
      <div class="icon"><i class="fa fa-upload" aria-hidden="true"></i></div>

      <div class="content">
        <h3><a href="{{url_for('views.upload')}}">How to upload text and documents</a></h3>
        <p>Here You can see a </p>
      </div>
    </div>
    <div class="box">
      <div class="icon"><i class="fa fa-rocket" aria-hidden="true"></i></div>
      <div class="content">
        <h3><a href="{{url_for('views.guidence')}}">Detection Guidence</a></h3>
        <p>Here You can see a vedio of our model detecting abusive words </p>
      </div>
    </div>
    <div class="box">
      <div class="icon"><i class="fa fa-question-circle" aria-hidden="true"></i></div>
      <div class="content">
        <h3><a href="">Queries</a></h3>
        <p>For any kinds of Queries or Feedbacks</p>
      </div>

    </div>
  </div>
</body>
  
{% endblock content %}

website/templates/login.html
{% extends 'baseHome.html' %} {% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Log In</title>
    <!-- stylesheet -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/login.css') }}"
    />
    <!-- materials icon -->
    <!-- https://fonts.google.com/icons?icon.style=Sharp&icon.query=close -->
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp"
      rel="stylesheet"/>
</head>
 <body>
        <div class="container"> 
        <form action="/login" method="post">
        <h1>Log In to your Account</h1>

    <label for="email">Email Address</label>
          <input type="email" placeholder="Enter Email" name="email" id="email" required>
          <label for="password">Password</label>
          <input type="password" placeholder="Enter Password" name="password" maxlength="12" id="password" required>
          <button type="submit"><b>Submit</b></button>
        <div class="signup_link">
         No Account? Sign Up <a href="{{url_for('views.SignUp')}}">Here</a>
       <br><a href="{{url_for('views.reset_pass')}}">Reset Password?</a>
        
      </div>
       </div> 
      </form>
    </div>
    
  </body>
        </html>
        {% endblock content %}